GET http://localhost:3000/api/users

###

POST http://localhost:3000/api/jobs
Content-Type: application/json

{
  "title": "Hello World",
  "authorEmail": "alice@prisma.io"
}

###

PUT  http://localhost:3000/update/22

###

PUT http://localhost:3000/post/1/views

###

PUT http://localhost:3000/publish/5

###

GET http://localhost:3000/user/3/drafts

###

GET http://localhost:3000/job/1